[package]
name = "hand-isomorphism-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cdrs-tokio = { version = "8.1.2", features = ["derive"] }
lazy_static = "1.4.0"
tokio = "1.36.0"
