[package]
name = "hand-isomorphism-rust"
version = "0.1.0"
edition = "2021"
authors = ["Floris Kappen kappenfloris@gmail.com"]

[dependencies]
lazy_static = "1.4.0"

[lib]
name = "hand_isomorphism_rust" # The name of the library
path = "src/lib.rs" # Path to the root of your library crate
